FROM tensorflow/tensorflow:2.10.1-gpu

ENV NCCL_P2P_DISABLE 1

RUN pip install scipy==1.10.1
RUN pip install tqdm==4.66.1
RUN pip install opencv-python-headless==4.8.1.78
RUN pip install pandas==2.0.3
RUN pip install pillow==10.1.0
